### ISSUE TITLE
Allow configuration in .slashdeploy.yml to define the default environment.

### ISSUE THREAD

**Issue by russellballestrini** [remind101/slashdeploy#111]
```
# For information about what configuration options are available, see
# https://slashdeploy.io/docs
default_environment: production
environments:
  production:
    aliases:
      - prod
```

This will allow us to assume things about a project, and enable easier to use commands like #46's `/deploy lock <repo>` command.
