### ISSUE TITLE
.slashdeploy.yml in repo root

### ISSUE THREAD

**Issue by ejholmes** [remind101/slashdeploy#94]
Right now, setting up things like continuous delivery is kinda a pain since there's no UI whatsoever. I think it might be cool if repositories could just configure SlashDeploy settings in a `.slashdeploy.yml` file in the root, ala most CI systems. For example:

```yaml
environments:
  production:
    aliases:
      - prod
    # Automatically deploy the master branch to the "production" environment
    # once ci/circleci and container/docker are passing.
    continous_delivery:
      ref: ref/heads/master
      required_contexts:
        - ci/circleci
        - container/docker
  staging:
    aliases:
      - stage
    # Automatically deploy the develop branch to the "staging" environment.
    continous_delivery:
      ref: ref/heads/develop
```

This would fix https://github.com/remind101/slashdeploy/issues/50
